version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: movies_user
      POSTGRES_PASSWORD: movies_pass
      POSTGRES_DB: movies_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movies_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_NAME: movies_db
      DATABASE_USER: movies_user
      DATABASE_PASSWORD: movies_pass
    ports:
      - "80:80"
    volumes:
      - ./:/app
    command: ["sh", "-c", "sh ./scripts/wait-for-db.sh && python app.py"]

  populate:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_NAME: movies_db
      DATABASE_USER: movies_user
      DATABASE_PASSWORD: movies_pass
    volumes:
      - ./:/app
      - data:/data
    command: ["sh", "-c", "sh ./scripts/wait-for-db.sh && sh ./scripts/download_and_populate.sh /data"]

volumes:
  db_data:
  data:
